
# SEO settings
title: "Philosymbol's "
title2: "Blog" # default: ""
description: "Tech Notes"
keywords: "dev,opeartion,system,security,web"
url: http://swjo207.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: https://github.com/swjo207/swjo207.github.io
disqus_shortname: "disqus_OV2hsRQf9L"
twitter_username: "swjo207"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "sangwon jo"
  job      : "Software Engineer"
  bio      : "multi-variant programmer, and system designer"
  thumb    : /images/author.jpg
  email    : swjo207@gmail.com
  url      : http://swjo207.github.io
  github   : http://github.com/swjo207
  twitter  : http://twitter.com/swjo207
  facebook : https://www.facebook.com/swjo207
  linkedin : https://www.linkedin.com/in/swjo207

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@swjo207"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
